### ISSUE TITLE
Can't pair Sony Sixaxis Gamepad

### ISSUE THREAD

**Issue by Para-Doxe** [OpenELEC/service.openelec.settings#14]
With the new version of OpenElec Settings Add-on, I can pair easily Bluetooth device.

But not a Sony Sixaxis Gamepad. I tested it on my Gnu/Linux Laptop and it work. But not in OpenElec Settings Add-on.

**Comment by chewitt** [comment]
I'm closing this down due to elapsed time with no update. Thanks.
