### ISSUE TITLE
service.openelec.settings not responding after screensaver was activated

### ISSUE THREAD

**Issue by mariefischer** [OpenELEC/service.openelec.settings#51]
OpenELEC settings plugin is working OK until the screensaver is activated. After returning from screensaver, the OpenELEC settings menu item will not open any more. If the settings menu is open while screensaver is activated, it is not possible to return to the main menu any more. After reboot, it works again.

It also seems that bluetooth standby (Sony PS3 BD Remote) does not work because of this - the remote will be awake and continue consuming ~ 13mA.

This happens on fresh installs of both OpenELEC 4.0.7 and 4.2.0 (service.openelec.settings version 0.3.x) on a Raspberry PI. On OpenELEC 3.2.4 with addon version 0.2.20 everything is fine - settings menu works after returning from screensaver and bluetooth remote goes to sleep nicely, consuming just ~ 0.13 mA.

Google didn't find anything about such an issue. Please let me know what I can do to debug it.

I turned on debug logging in XBMC, here are some fragments (from 4.0.7):

02:10:51 T:2869949520  NOTICE: Thread LanguageInvoker start, auto delete: false
02:10:51 T:2869949520    INFO: initializing python engine.
02:10:51 T:2869949520   DEBUG: CPythonInvoker(1, /usr/share/xbmc/addons/service.openelec.settings/default.py): start processing
02:10:52 T:2869949520  NOTICE: -->Python Interpreter Initialized<--
02:10:52 T:2869949520   DEBUG: CPythonInvoker(1, /usr/share/xbmc/addons/service.openelec.settings/default.py): the source file to load is /usr/share/xbmc/addons/service.openelec.settings/default.py
02:10:52 T:2869949520   DEBUG: CPythonInvoker(1, /usr/share/xbmc/addons/service.openelec.settings/default.py): setting the Python path to /usr/share/xbmc/addons/service.openelec.settings:/usr/share/xbmc/addons/script.module.pil/lib:/usr/share/xbmc/addons/xbmc.debug/:/usr/lib/python27.zip:/usr/lib/python2.7:/usr/lib/python2.7/plat-linux2:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/lib/python2.7/site-packages:/usr/lib/python2.7/site-packages/PIL:/usr/lib/python2.7/site-packages/gtk-2.0
02:10:52 T:2869949520   DEBUG: CPythonInvoker(1, /usr/share/xbmc/addons/service.openelec.settings/default.py): entering source directory /usr/share/xbmc/addons/service.openelec.settings
02:10:52 T:2869949520   DEBUG: CPythonInvoker(1, /usr/share/xbmc/addons/service.openelec.settings/default.py): instantiating addon using automatically obtained id of "service.openelec.settings" dependent on version 2.1.0 of the xbmc.python api
02:10:52 T:2869949520    INFO: CPythonInvoker(1, /usr/share/xbmc/addons/service.openelec.settings/default.py): script successfully run
02:10:52 T:2869949520    INFO: Python script stopped
02:10:52 T:2869949520   DEBUG: Thread LanguageInvoker 2869949520 terminating
02:10:52 T:3058184192   DEBUG: ------ Window Init (/usr/share/xbmc/addons/service.openelec.settings/resources/skins/Default/720p/mainWindow.xml) ------
02:10:52 T:3058184192    INFO: Loading skin file: /usr/share/xbmc/addons/service.openelec.settings/resources/skins/Default/720p/mainWindow.xml, load type: LOAD_ON_GUI_INIT
02:10:53 T:3058184192   DEBUG: POParser: loaded 277 strings from file /usr/share/xbmc/addons/service.openelec.settings/resources/language/English/strings.po
02:10:53 T:2935923792   DEBUG: Previous line repeats 13 times.
02:10:53 T:3058184192   DEBUG: CGUIMediaWindow::GetDirectory ()
02:10:53 T:3058184192   DEBUG:   ParentPath = []
02:10:53 T:3058184192   ERROR: Control 1000 in window 13001 has been asked to focus, but it can't
02:10:53 T:3058184192   DEBUG: Activating window ID: 10138
02:10:53 T:3058184192   DEBUG: ------ Window Init (DialogBusy.xml) ------
02:10:53 T:2836395088   DEBUG: POParser: loaded 277 strings from file /usr/share/xbmc/addons/service.openelec.settings/resources/language/English/strings.po
[...]
02:11:51 T:3058184192   DEBUG: CAnnouncementManager - Announcement: OnScreensaverActivated from xbmc
02:11:51 T:3058184192   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverActivated
02:11:51 T:3058184192   DEBUG: ------ Window Init () ------
[...]
02:11:52 T:3058184192   DEBUG: CAnnouncementManager - Announcement: OnScreensaverDeactivated from xbmc
02:11:52 T:3058184192   DEBUG: GOT ANNOUNCEMENT, type: 4, from xbmc, message OnScreensaverDeactivated
02:11:52 T:3058184192   DEBUG: Activating window ID: 10138
02:11:52 T:3058184192   DEBUG: ------ Window Init (DialogBusy.xml) ------
02:11:52 T:3058184192   DEBUG: ------ Window Deinit (DialogBusy.xml) ------
02:11:52 T:3058184192   DEBUG: ------ Window Deinit () ------
02:11:52 T:3058184192   DEBUG: Activating window ID: 10138
02:11:52 T:3058184192   DEBUG: ------ Window Init (DialogBusy.xml) ------
02:11:52 T:3058184192   DEBUG: ------ Window Deinit (DialogBusy.xml) ------

**Comment by chewitt** [comment]
I'm closing this ticket due to elapsed time with no update. If this is still a problem please open a thread in the forums. Thanks.
