### ISSUE TITLE
Can't connect wiimote anymore

### ISSUE THREAD

**Issue by GerbenWelter** [OpenELEC/service.openelec.settings#52]
With OE 4.x I can't connect the wiimote anymore by using the 1+2 button combination. I can only get it to connect by using the OE settings/bluetooth menu (using a mouse) and choosing 'trust & connect'. After that I can use the wiimote. But if I turn the wiimote off or reboot OE the wiimote can't connect itself again.

This used to work but was probably by virtue of the xbmc-wiimote add-on. Even through upgrades from 3.x to 4.x. Only upgrading to 4.2.x finally broke the wiimote functionality. I tried a clean install of 4.2.1 but that didn't help. I also can't completely revert to 3.2 or 4.0 because the xbmc-wiimote addon doesn't seem to be available anymore.

**Comment by aizelauna** [comment]
Here is a procedure that worked for me with OpenELEC 5.0.5 :
- The key is not to use 1+2 to connect but to use the sync button on the remote the first time for pairing it.
- Then just press the connect button in the OpenElec Bluetooth options. 
- After that first pairing with the sync button my Wiimote just connects with OpenELEC by pressing any button, not 1+2.

Source :
http://openelec.tv/forum/104-bluetooth-remotes/66221-wii-remote-won-t-work-as-i-expect#90658

**Comment by tomchiverton** [comment]
Still broken on a Pi3 and the OpenElec image.
