### ISSUE TITLE
Samba configuration

### ISSUE THREAD

**Issue by smory** [OpenELEC/service.openelec.settings#53]
It would great if Samba could be better configured in xbmc than it is now. Prefereably to have a new window in which all settings which are currently in samba.conf could be manipulated.

If this would be accepted, I can work on this.

**Comment by chewitt** [comment]
If you wanted to enhance samba capabilities (e.g. allow GUI driven selection of what to share) we would be interested, but for now I am closing the ticket due to lack of update. Thanks.
