### ISSUE TITLE
Add RunScript() parameters

### ISSUE THREAD

**Issue by Nessus85100** [OpenELEC/service.openelec.settings#55]
Is it possible to add some RunScript() parameters so we can open certain parts of the addon from a onclick skin action. For example:

- RunScript(service.openelec.settings?action=editconnection)
This could open only the "Edit" window in "Connections"  so you can change your connection settings.

- RunScript(service.openelec.settings?action=updatecheck)
This can check for any system updates.

Cheers
Nessus

**Comment by chewitt** [comment]
I'm closing this ticket as there are no current plans to add this functionality. Thanks.
