### ISSUE TITLE
Network Connections Settings Bug 5.0.8 RPi2

### ISSUE THREAD

**Issue by ngodber** [OpenELEC/service.openelec.settings#65]
Tried to configure IPv4 settings to manual (using network switch) for eth0, system allows user to edit, select manual and enter IP and Subnet however on selecting either 'save' or 'connect' prompt closes and the settings are not retained (type remains 'dhcp' and not changes can be seen). Have tried saving and immediately restarting, without success.

I believe the system should save the manual settings and show type 'manual' on 'Connections' screen with the specified address displayed

**Comment by ngodber** [comment]
Note, cannot upload logs due to lack of network access.

**Comment by stefansaraev** [comment]
I'll close this, reopened https://github.com/OpenELEC/OpenELEC.tv/issues/4081
