### ISSUE TITLE
backup .ssh folder

### ISSUE THREAD

**Issue by Yannik** [OpenELEC/service.openelec.settings#68]
Hi,

[BACKUP_DIRS](https://github.com/OpenELEC/service.openelec.settings/blob/master/src/defaults.py#L94), which is used in [do_backup](https://github.com/OpenELEC/service.openelec.settings/blob/master/src/resources/lib/modules/system.py#L649) includes `XBMC_USER_HOME`, `USER_CONFIG` and `CONFIG_CACHE`.

`CONFIG_CACHE` does include `./services/sshd.conf`.

If you disable ssh password authentication in `./services/sshd.conf` as recommended, then backup and restore your configuration, you will be locked out from ssh, as the `.ssh` folder which includes the `authorized_keys` is not backed up.

Because of this it would be very good to backup the `.ssh` folder as well.

Thanks
Yannik

**Comment by Yannik** [comment]
I created a PR for this: https://github.com/OpenELEC/service.openelec.settings/pull/69

**Comment by stefansaraev** [comment]
I dont think this is good idea. you can always re-enable password auth and do ssh-copy-id.

@lfiebach @sraue what do you think ?

**Comment by Yannik** [comment]
@stefansaraev Can you elaborate why you think this is a bad idea? Reenabling password auth without ssh access seems to be quite complicated for the user. Apparantly it's not possible to easily access a local shell with `CTRL+ALT+..`, but requires adding a option to cmdline.txt which then again would require the user to first notice that the ssh login doesn't work, shutdown the pi, physically remove the sdcard and edit the cmdline.txt manually and so on. This seems to be quite a hassle.

**Comment by stefansaraev** [comment]
reenabling password auth is easy and possible via GUI. 

on my set-up, I have private keys in .ssh, I am not sure I want those to end up in backups. that's of course, my personal opinion, if @sraue agrees with #69 - I wont protest ;)

**Comment by Yannik** [comment]
I hope your private keys are encrypted? ;-)

**Comment by stefansaraev** [comment]
thinking again about it, this is very valid point. tanks for taking the time to report (and sending a PR). added in 61ef74538e260fa271873b1595e9d54a6aa0a18e

**Comment by Yannik** [comment]
@stefansaraev Thanks. Can you give me a heads up in which addon repo this addon is located?

**Comment by stefansaraev** [comment]
none. iit's part of openelec. the fix will be available next beta.
